version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy:1.5.1
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/docker/proxy/web.test.local:/etc/nginx/vhost.d/web.test.local
      - proxy:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    environment:
      TZ: Asia/Tokyo
      DHPARAM_GENERATION: false
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/docker/proxy/web.test.local:/etc/nginx/vhost.d/web.test.local
      - proxy:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
    depends_on:
      - proxy

  php:
    build:
      context: ./docker/laravel
    platform: linux/amd64
    volumes:
      - $PWD/laravel:/var/www/html
      - php_vendor:/var/www/html/vendor
    environment:
      TZ: Asia/Tokyo
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      APP_ENV: local
      APP_DEBUG: true
      APP_NAME: Laravel
      APP_URL: https://web.test.local
    depends_on:
      - db
      - proxy
    command: >
      sh -c "
      ./init.sh &&
      php-fpm
      "

  web:
    image: nginx:1.10.3
    volumes:
      - $PWD/docker/laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/laravel:/var/www/html
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: web.test.local
      CERT_NAME: default
    depends_on:
      - php
      - proxy

  nextjs:
    build: 
      context: ./docker/nextjs
    volumes:
      - $PWD:/app
      - node_modules:/app/nextjs/node_modules
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: next.test.local
      CERT_NAME: default
      AUTH_SECRET: some-secret
      AUTH_URL: https://web.test.local/login-next
      ALLOWED_IPS: ${ALLOWED_IPS:-192.168.65.1/16}
    working_dir: /app/nextjs
    tty: true
    depends_on:
      - proxy
    command:  >
      sh -c "
      npm i &&
      npm run dev -- -p 80
      "

  db:
    image: mysql:8.0.30
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  proxy:
  certs:
  db-store:
  node_modules:
    name: nextjs-laravel-auth-node_modules
    driver: local
  php_vendor:
    name: nextjs-laravel-auth-php_vendor
    driver: local
